StaminaSiphon:
  weight: 1
  color: [0.87, 0.84, 0.28, 1]  # Yellow-Gold

EitrSiphon:
  weight: 1
  color: [0.73, 0.19, 0.77, 1]  # Purple

ShieldBreaker:
  weight: 1
  color: [0.87, 0.84, 0.28, 1]  # Yellow-Gold

IgnoreArmor:
  weight: 1
  color: [0.88, 0.01, 0.15, 1]  # Red

FoodDrain:
  weight: 1
  color: [0.88, 0.01, 0.15, 1]  # Red

FireInfused:
  weight: 1
  color: [0.88, 0.01, 0.15, 1]  # Red

FrostInfused:
  weight: 1
  color: [0.32, 0.66, 0.91, 1]  # Blue

PoisonInfused:
  weight: 1
  color: [0.18, 0.55, 0.24, 1]  # Green

LightningInfused:
  weight: 1
  color: [0.87, 0.84, 0.28, 1]  # Yellow-Gold

RemoveStatusEffect:
  weight: 1
  color: [0.73, 0.19, 0.77, 1]  # Purple

PersonalShield:
  weight: 1
  color: [0.88, 0.01, 0.15, 1]  # Red

ShieldDome:
  weight: 0
  color: [0.87, 0.84, 0.28, 1]  # Yellow-Gold

SoulEater:
  weight: 1
  color: [0.88, 0.01, 0.15, 1]  # Red

FastMovement:
  weight: 1
  color: [0.88, 0.01, 0.15, 1]  # Red

FastAttackSpeed:
  weight: 1
  color: [0.87, 0.84, 0.28, 1]  # Yellow-Gold

DistantDetection:
  weight: 1
  color: [0.73, 0.19, 0.77, 1]  # Purple

ElementalImmunity:
  weight: 1
  color: [0.73, 0.19, 0.77, 1]  # Purple

PierceImmunity:
  weight: 1
  color: [0.88, 0.01, 0.15, 1]  # Red
  
SlashImmunity:
  weight: 1
  color: [0.88, 0.01, 0.15, 1]  # Red
  
BluntImmunity:
  weight: 1
  color: [0.88, 0.01, 0.15, 1]  # Red

StaggerImmune:
  weight: 1
  color: [0.87, 0.84, 0.28, 1]  # Yellow-Gold

PoisonDeath:
  weight: 1
  color: [0.18, 0.55, 0.24, 1]  # Dark Green

FireDeath:
  weight: 1
  color: [0.88, 0.01, 0.15, 1]  # Red

FrostDeath:
  weight: 1
  color: [0.32, 0.66, 0.91, 1]  # Blue
  
HealDeath:
  weight: 1
  color: [0.73, 0.19, 0.77, 1]  # Purple

StaggerDeath:
  weight: 1
  color: [0.87, 0.84, 0.28, 1]  # Yellow-Gold

TarDeath:
  weight: 1
  color: [0.22, 0.15, 0.04, 1]  # Brown
  
BloodLoss:
  weight: 1
  color: [0.88, 0.01, 0.15, 1]  # Red
  
Absorption:
  weight: 1
  color: [0.32, 0.66, 0.91, 1]  # Blue
  
Vampiric:
  weight: 1
  color: [0.88, 0.01, 0.15, 1]  # Red
  
Forceful:
  weight: 1
  color: [0.22, 0.15, 0.04, 1]  # Brown